[".zprezto"]
    type = "git-repo"
    url = "https://github.com/rbgarga/prezto.git"
    refreshPeriod = "24h"
    exact = true
    clone.args = ["--recurse-submodules"]
    pull.args = ["--recurse-submodules"]
    update = true
